version: '3.9'

services:
  backend:
    image: ghcr.io/boostcampwm2025/web02-CMC-backend:latest
    environment:
      PORT: 3000
    ports:
      - '3000:3000'
    restart: unless-stopped

  frontend:
    image: ghcr.io/boostcampwm2025/web02-CMC-frontend:latest
    ports:
      - '80:80'
    depends_on:
      - backend
    restart: unless-stopped
