export const BATTLE_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  FINISHED: 'FINISHED',
} as const

export const BATTLE_PHASE = {
  WAITING_FOR_START: 'WAITING_FOR_START',
  OPINION_SHARE: 'OPINION_SHARE',
  TEAM_A_ATTACK: 'TEAM_A_ATTACK',
  TEAM_B_ATTACK: 'TEAM_B_ATTACK',
  TEAM_SWITCH: 'TEAM_SWITCH',
} as const
