export const BATTLE_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  FINISHED: 'FINISHED',
} as const

export const BATTLE_PHASE = {
  WAITING_FOR_START: 'WAITING_FOR_START',
  OPINION_SHARE: 'OPINION_SHARE',
  TEAM_A_ATTACK: 'TEAM_A_ATTACK',
  TEAM_B_ATTACK: 'TEAM_B_ATTACK',
  TEAM_SWITCH: 'TEAM_SWITCH',
} as const
export enum BATTLE_LANGUAGE {
  TS = 'TS',
  JS = 'JS',
  PYTHON = 'PYTHON',
}

export enum BATTLE_TYPE {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
}

export enum BATTLE_CATEGORY {
  ALGORITHM = 'ALGORITHM',
  REFACTORING = 'REFACTORING',
  IMPLEMENT = 'IMPLEMENT',
  ETC = 'ETC',
  //추후 더 추가
}

export enum BATTLE_PLAYTIME {
  FIVE_MIN = 5,
  TEN_MIN = 10,
  THIRTY_MIN = 30,
}

export enum BATTLE_STATUS {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
}

export enum TEAM {
  A = 'A',
  B = 'B',
  NONE = 'NONE',
}
